# Generated by Django 5.1.5 on 2025-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(default="default_value", max_length=255, null=True),
        ),
    ]
