# Generated by Django 5.1.5 on 2025-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_producto_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
