# Generated by Django 5.1.5 on 2025-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_producto_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
