# Generated by Django 5.1.5 on 2025-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_producto_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telefono",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
