# Generated by Django 5.1.5 on 2025-01-25 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_venta_total_alter_profile_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="total",
        ),
    ]
