# Generated by Django 5.1.5 on 2025-01-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_opinioncliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="talla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.productotalla",
            ),
        ),
    ]
