# Generated by Django 5.1.5 on 2025-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_venta_cantidad_remove_venta_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineaventa",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
