# Generated by Django 5.1.5 on 2025-02-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_alter_lineaventa_precio_unitario_alter_venta_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="colores/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="acepta_terminos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lineaventa",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.color",
            ),
        ),
        migrations.CreateModel(
            name="ProductoTallaColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.color"
                    ),
                ),
                (
                    "producto_talla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colores",
                        to="web.productotalla",
                    ),
                ),
            ],
        ),
    ]
