# Generated by Django 5.1.5 on 2025-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_remove_productotalla_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
