# Generated by Django 5.1.5 on 2025-02-25 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_alter_producto_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="color",
            name="imagen",
        ),
    ]
