# Generated by Django 5.1.5 on 2025-02-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="pago",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.pago",
            ),
        ),
    ]
