# Generated by Django 5.1.5 on 2025-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_venta_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="envio",
            field=models.CharField(
                choices=[
                    ("envio", "Envío a domicilio"),
                    ("retiro", "Retiro en tienda"),
                ],
                default="envio",
                max_length=20,
            ),
        ),
    ]
